### ISSUE TITLE
Bedrock outdated

### ISSUE THREAD

**Issue by aubymori** [Crackers0106/Programmer-Art-Plus#11]
The Bedrock version of the pack is still on 1.17, while the Java version is on 1.19. It shouldn't be that much of a hassle to just port the new textures over to the Bedrock version of the pack.

**Comment by inteneich** [comment]
Bedrock is outdated due to the fact, that I have stopped a development of it for now. Latest version I've made is based on 1.18, but it is newer than in the Bedrock branch

**Comment by aubymori** [comment]
I might be able to update the pack and make a PR, but it would be greatly appreciated if you could update the Bedrock branch to the 1.18 version.

**Comment by inteneich** [comment]
1.6.1 (the latest version that I have) is for 1.18.x. Link is here: https://github.com/Typical0/Programmer-Art-Plus/releases/tag/v1.6.1

**Comment by aubymori** [comment]
Alright. I'll check it out when I get home.

**Comment by Crackers0106** [comment]
A version for Bedrock 1.19 equal to v2.4.0 can be found here: https://github.com/Typical0/Programmer-Art-Plus/releases
I'm keeping this open because a port for 1.20 has not been made yet

**Comment by inteneich** [comment]
The new version of Bedrock port was released. It can be found here: https://github.com/Typical0/MCT-Plus/releases/tag/v1.8.1.
