### ISSUE TITLE
Leaves don't render properly when using Fast graphics mode with Sodium

### ISSUE THREAD

**Issue by inteneich** [Crackers0106/Programmer-Art-Plus#13]
As stated in the title, leaves do not properly render when using Fast graphics mode with any Sodium 0.5.x version. Tested it under 1.20.1 (with Sodium 0.5.3) and 1.20.4 (Sodium 0.5.5).

![2024-01-06_19 59 43](https://github.com/Crackers0106/Programmer-Art-Plus/assets/81305501/4cd61f60-e04e-4da1-9402-08ce6fb31d50)

1.20.1, Sodium 0.5.3 and PA+ v2.5.0, using Fancy graphics mode for leaves.

![2024-01-06_19 59 51](https://github.com/Crackers0106/Programmer-Art-Plus/assets/81305501/560c4d92-baf0-421c-9923-9aabea6ec4e1)

The same configuration as above, which is using Fast graphics mode for leaves.

![2024-01-06_20 00 01](https://github.com/Crackers0106/Programmer-Art-Plus/assets/81305501/b42f161b-b20b-4d72-b40d-d3d7005664ca)

The same scenario with Programmer Art, using Fast graphics mode for leaves.

![2024-01-06_20 00 08](https://github.com/Crackers0106/Programmer-Art-Plus/assets/81305501/d332e056-02f4-42a0-a910-e0e4244ef84f)

Without any resource packs applied, using Fast graphics mode for leaves.

**Comment by Crackers0106** [comment]
Can you check the repo version of the pack to see if this still happens there, rather than the latest release?

**Comment by inteneich** [comment]
The issue is fixed in the repo version. Closing the issue.
