### ISSUE TITLE
Outdated source?

### ISSUE THREAD

**Issue by ghost** [Crackers0106/Programmer-Art-Plus#2]
Despite there being new releases, the `src/` directory is outdated (git reports it being last updated 15 months ago). Ideally you should be working and commiting in this directory and building the release pack from it, so the source is always up to date with releases.

**Comment by Crackers0106** [comment]
I know, I would like a more efficient way to do it. I have a dev folder that I use where I'm constantly refreshing the textures and I need to find a way for it to automatically commit changes I make

**Comment by ghost** [comment]
Just have the dev folder located within the repository (or on a separate branch) and commit every time you make changes. That's the whole point of Git. You could even have the resource pack being loaded in game just be a Git repository.
